package pe.colegio.util;

public enum EstadoType {
	ACTIVE, INACTIVE, BLOCKED, DELETED, // PARA LOS USUARIOS, APODERADOS y DOCENTES
	ASIGNADA, COMPLETADA, REVISION, APROBADA, RECHAZADA, ATRASADA, CANCELADA, // PARA LAS TAREAS DE LOS ESTUDIANTES
	A, T, F, J, // PARA ASISTENCIA
	LEIDA, NO_LEIDA, BORRAR, // PARA NOTIFICACION 
	URGENTE, AUTOMATICA, ALERTA; // PARA TIPO DE NOTIFICACION
}
