package pe.colegio.util;

public enum EstadoType {
	ACTIVE, INACTIVE, BLOCKED, DELETED, // PARA LOS USUARIOS, APODERADOS y DOCENTES
	ASIGNADA, COMPLETADA, REVISION, APROBADA, RECHAZADA, ATRASADA, CANCELADA; // PARA LAS TAREAS DE LOS ESTUDIANTES
}
